Update to 5.15-21.08 runtime + deps (take 2)
flathub/com.ozmartians.VidCutter pull request #27
Opened 2022-04-30 09:15 UTC by ozmartian

2022-04-30 09:49 UTC, ozmartian commented
Issue logged at:

https://github.com/flathub/flathub/issues/3082

2022-04-30 19:57 UTC, hfiguiere commented
The icons are in `share/icons/icons/hicolor/128x128/apps/com.ozmartians.VidCutter.png` which is not the right path.

2022-05-01 00:18 UTC, hfiguiere requested changes

2022-05-01 00:18 UTC, hfiguiere commented on com.ozmartians.VidCutter.json
> +            "cp data/desktop/com.ozmartians.VidCutter.desktop ${FLATPAK_DEST}/share/applications"
```suggestion
            "cp -R data/icons/hicolor ${FLATPAK_DEST}/share/icons/",
            "install -Dm644 -t ${FLATPAK_DEST}/share/applications data/desktop/com.ozmartians.VidCutter.desktop"
```

2022-05-01 01:02 UTC, hfiguiere commented
bot, build

2022-05-01 01:03 UTC, hfiguiere commented
builds where cancelled so we don't actually know if your last changes did work.

2022-05-01 01:06 UTC, hfiguiere commented on com.ozmartians.VidCutter.json
> +            "cp data/desktop/com.ozmartians.VidCutter.desktop ${FLATPAK_DEST}/share/applications"
I don't think these are neccessary tbf. Let's see how the current build do. (all previous were cancelled)

2022-05-01 02:31 UTC, ozmartian commented
> builds where cancelled so we don't actually know if your last changes did work.

2022-05-01 04:23 UTC, hfiguiere commented
I think you also need this change:

https://github.com/flathub/com.ozmartians.VidCutter/pull/28/commits/91b2007c0dc0c37345800255b68311b5b60e793b#diff-21095ac5afedb596a89240f2348545ba529031a43ff7ebab366c4742aca743d1R90

2022-05-01 04:41 UTC, closed without merging